export const streamingLinks = [
  {
    name: '멜론',
    logo: '/melon.png',
    androidLinks: [
      'https://iii.ad/288ef0',
      'https://iii.ad/f9d8cc',
      'https://iii.ad/288ef0',
      'https://iii.ad/f254d0',
      'https://iii.ad/46b186',
    ],
    iphoneLinks: ['https://iii.ad/f1f027'],
    ipadLinks: ['https://iii.ad/c003bd'],
    windowLinks: [
      'https://iii.ad/c22ffc',
      'https://iii.ad/78ac0f',
      'https://iii.ad/c22ffc',
      'https://iii.ad/50a0a0',
      'https://iii.ad/ea1f04',
    ],
    macLinks: [
      'https://iii.ad/bcd504',
      'https://iii.ad/fbf6f1',
      'https://iii.ad/bcd504',
      'https://iii.ad/c5c1a9',
      'https://iii.ad/279d05',
    ],
  },
  {
    name: '지니',
    logo: '/genie.png',
    androidLinks: ['https://lrl.kr/Urnr'],
    iphoneLinks: ['https://lrl.kr/cWjKn'],
    ipadLinks: [],
    windowLInks: ['https://vo.la/AKLZlW'],
    macLinks: [],
  },
  {
    name: '벅스',
    logo: '/bugs.png',
    androidLinks: ['https://vo.la/gcsNvi'],
    iphoneLinks: ['https://vo.la/gcsNvi'],
    ipadLinks: ['https://vo.la/gcsNvi'],
    windowLinks: ['https://vo.la/gcsNvi'],
    macLinks: ['https://vo.la/gcsNvi'],
  },
  {
    name: '플로',
    logo: '/flo.png',
    androidLinks: ['https://lrl.kr/eieEa'],
    iphoneLinks: ['https://lrl.kr/eieEa'],
    ipadLinks: ['https://lrl.kr/eieEa'],
    windowLinks: [],
    macLinks: [],
  },
  {
    name: '바이브',
    logo: '/vibe.png',
    androidLinks: [
      'https://vo.la/MGUHqj',
      'https://vo.la/lAoNiG',
      'https://vo.la/MGUHqj',
      'https://vo.la/hEdhPS',
      'https://vo.la/AAAkiz',
    ],
    iphoneLinks: [
      'https://vo.la/MGUHqj',
      'https://vo.la/lAoNiG',
      'https://vo.la/MGUHqj',
      'https://vo.la/hEdhPS',
      'https://vo.la/AAAkiz',
    ],
    ipadLinks: [
      'https://vo.la/MGUHqj',
      'https://vo.la/lAoNiG',
      'https://vo.la/MGUHqj',
      'https://vo.la/hEdhPS',
      'https://vo.la/AAAkiz',
    ],
    windowLinks: [
      'https://vo.la/MGUHqj',
      'https://vo.la/lAoNiG',
      'https://vo.la/MGUHqj',
      'https://vo.la/hEdhPS',
      'https://vo.la/AAAkiz',
    ],
    macLinks: [
      'https://vo.la/MGUHqj',
      'https://vo.la/lAoNiG',
      'https://vo.la/MGUHqj',
      'https://vo.la/hEdhPS',
      'https://vo.la/AAAkiz',
    ],
  },
];
