export const streamingLinks = [
  {
    name: '멜론',
    logo: '/melon.png',
    androidLinks: [
      'https://vo.la/wWRpeQ',
      'https://vo.la/TyPvIX',
      'https://vo.la/rkxCnA',
      'https://vo.la/KfCDZp',
      'https://vo.la/YHinAe',
      'https://vo.la/GcsZdA]',
    ],
    iphoneLinks: ['https://vo.la/ZaMBPP'],
    ipadLinks: ['https://lrl.kr/mz1I'],
    windowLinks: [
      'https://vo.la/umrqGP',
      'https://vo.la/jkYTcB',
      'https://vo.la/ewBDsV',
      'https://lrl.kr/DmBV',
      'https://lrl.kr/HyKY',
      'https://lrl.kr/inSN',
    ],
    macLinks: [
      'https://lrl.kr/uZGj',
      'https://lrl.kr/qNxl',
      'https://lrl.kr/mBoq',
      'https://lrl.kr/uZGj',
      'https://lrl.kr/zbPy',
      'https://lrl.kr/mBot ',
    ],
  },
  {
    name: '지니',
    logo: '/genie.png',
    androidLinks: ['https://vo.la/yYPOhs'],
    iphoneLinks: ['https://lrl.kr/inSH'],
    ipadLinks: [],
    windowLInks: ['https://vo.la/bTcyXO'],
    macLinks: [],
  },
  {
    name: '벅스',
    logo: '/bugs.png',
    androidLinks: ['https://vo.la/TSvYHq'],
    iphoneLinks: ['https://vo.la/TSvYHq'],
    ipadLinks: ['https://vo.la/TSvYHq'],
    windowLinks: ['https://vo.la/TSvYHq'],
    macLinks: ['https://vo.la/TSvYHq'],
  },
  {
    name: '플로',
    logo: '/flo.png',
    androidLinks: [],
    iphoneLinks: [],
    ipadLinks: [],
    windowLinks: [],
    macLinks: [],
  },
  {
    name: '바이브',
    logo: '/vibe.png',
    androidLinks: [
      'https://vo.la/RUWjhA',
      'https://vo.la/FWNgoz',
      'https://vo.la/nfLWUn',
      'https://lrl.kr/LKTW',
      'https://lrl.kr/qMaN',
      'https://lrl.kr/HyKW',
    ],
    iphoneLinks: [
      'https://vo.la/RUWjhA',
      'https://vo.la/FWNgoz',
      'https://vo.la/nfLWUn',
      'https://lrl.kr/LKTW',
      'https://lrl.kr/qMaN',
      'https://lrl.kr/HyKW',
    ],
    ipadLinks: [
      'https://vo.la/RUWjhA',
      'https://vo.la/FWNgoz',
      'https://vo.la/nfLWUn',
      'https://lrl.kr/LKTW',
      'https://lrl.kr/qMaN',
      'https://lrl.kr/HyKW',
    ],
    windowLinks: [
      'https://vo.la/RUWjhA',
      'https://vo.la/FWNgoz',
      'https://vo.la/nfLWUn',
      'https://lrl.kr/LKTW',
      'https://lrl.kr/qMaN',
      'https://lrl.kr/HyKW',
    ],
    macLinks: [],
  },
];
