export const streamingLinks = [
  {
    name: "멜론",
    logo: "/melon.png",
    androidLinks: [
      "https://iii.ad/be6ef9",
      "https://iii.ad/c1b4d0",
      "https://iii.ad/be6ef9",
      "https://iii.ad/2ccb02",
    ],
    iphoneLinks: ["https://iii.ad/67f7ff"],
    ipadLinks: ["https://iii.ad/015dbd"],
    windowLinks: [
      "https://iii.ad/3c01ec",
      "https://iii.ad/9286eb",
      "https://iii.ad/3c01ec",
      "https://iii.ad/0d89d5",
    ],
    macLinks: [
      "https://iii.ad/c44ea8",
      "https://iii.ad/16074c",
      "https://iii.ad/c44ea8",
      "https://iii.ad/c186e4",
    ],
  },
  {
    name: "지니",
    logo: "/genie.png",
    androidLinks: ["https://iii.ad/e47147"],
    iphoneLinks: ["https://iii.ad/17c709"],
    ipadLinks: [],
    windowLInks: ["https://iii.ad/566064"],
    macLinks: [],
  },
  {
    name: "벅스",
    logo: "/bugs.png",
    androidLinks: ["https://iii.ad/d15251"],
    iphoneLinks: ["https://iii.ad/d15251"],
    ipadLinks: ["https://iii.ad/d15251"],
    windowLinks: ["https://iii.ad/c597d7"],
    macLinks: ["https://iii.ad/c597d7"],
  },
  {
    name: "플로",
    logo: "/flo.png",
    androidLinks: ["https://iii.ad/bd595d"],
    iphoneLinks: ["https://iii.ad/bd595d"],
    ipadLinks: ["https://iii.ad/bd595d"],
    windowLinks: [],
    macLinks: [],
  },
  {
    name: "바이브",
    logo: "/vibe.png",
    androidLinks: [
      "https://iii.ad/50ff56",
      "https://iii.ad/b9b4c7",
      "https://iii.ad/50ff56",
      "https://iii.ad/3bc944",
    ],
    iphoneLinks: [
      "https://iii.ad/50ff56",
      "https://iii.ad/b9b4c7",
      "https://iii.ad/50ff56",
      "https://iii.ad/3bc944",
    ],
    ipadLinks: [
      "https://iii.ad/50ff56",
      "https://iii.ad/b9b4c7",
      "https://iii.ad/50ff56",
      "https://iii.ad/3bc944",
    ],
    windowLinks: [
      "https://iii.ad/50ff56",
      "https://iii.ad/b9b4c7",
      "https://iii.ad/50ff56",
      "https://iii.ad/3bc944",
    ],
    macLinks: [
      "https://iii.ad/50ff56",
      "https://iii.ad/b9b4c7",
      "https://iii.ad/50ff56",
      "https://iii.ad/3bc944",
    ],
  },
];
