name: Auto Sync to Fork (narinn-star/adminwave)

on:
  push:
    branches:
      - main

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with fork
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ github.repositoryUrl }}
          source_branch: ${{ github.ref_name }}
          destination_repo: ${{ secrets.DESTINATION_GITHUB_URL }}
          destination_branch: ${{ github.ref_name }}
