name: Auto Sync to Fork

on:
  push:
    branches:
      - main

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with fork
        uses: wei/git-sync@v3
        with:
          source_repo: https://github.com/VIPwave/adminwave.git
          source_branch: main
          destination_repo: ${{ secrets.DESTINATION_GITHUB_URL }}
          destination_branch: main
